
language: java

sudo: required

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq texlive texlive-latex-extra texlive-lang-spanish
 - updatedb
 - locate currfile
 - echo LOCALIZADO CURRFILE

script: ./gradlew --debug check

