
language: java

sudo: required

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq texlive texlive-latex-extra texlive-lang-spanish
 - echo LOCALIZADO CURRFILE
 - find /etc | grep sty$

script: ./gradlew --debug check

