
language: java

sudo: required

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq texlive textlive-full texlive-latex-extra texlive-lang-spanish
 - echo LOCALIZADO CURRFILE

script: ./gradlew --debug check

